name: Test
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Setup Go
        uses: actions/setup-go@main
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: |
          CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o ./dynamic-config-ping-exporter .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Build container
        uses: docker/build-push-action@master
        with:
          context: .
          push: false
          tags: test
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      # - name: Test
      #   run: go test ./... -v -covermode=count